@startuml activite
start
:Image de départ en RGB;
split
    :Gaussian_blur();
    #SteelBlue:Passage en YUV;
    :EqualizeHist();
note left #FFAAAA: sur le canal Y
    #SteelBlue:Passage en HSV;
    :inRange();
note left #FFAAAA: Limites sur la couleur verte
    #SteelBlue:Masque binaire;
    :Dilate & Erode; 
    :Mask_final;
split again
end split
  :bitwise_and;
  :terrain;
stop
@enduml

