@startuml nom
start
group RGB
  if (image) then
  else
    :Gaussian_blur();
end
group HSV
    :EqualizeHist();
    :inRange();
    :Dilate & Erode; 
    :Mask_final;
end
  endif
  #palegreen:bitwise_and;
  :terrain;
stop
@enduml
